In [3]:
import pandas as pd

df = pd.read_csv("data/sales02.csv", nrows=10)

# 升序排序
df.sort_values(by="销售数量", ascending=True)  # 默认升序，ascending可以不写
# 降序排序
df.sort_values(by="销售数量", ascending=False)
# 多列排序
df.sort_values(by=["销售数量", "单价"], ascending=[True, False])

          订单号  产品类别  产品名称  销售数量   单价   销售额
9  5888085066    图书    字典     2   99   198
4  6801664364    食品    薯片     2   19    38
3  6823473137    食品    面包     3   29    87
5  5897064217    图书    字帖     4   29   116
2  5888085059  电子产品  智能音箱     5  399  1995
1  5857234132    食品    海苔     5   29   145
7  6898807429    服装    T恤     6  199  1194
6  6857752388    服装    袜子     7  -29  -203
8  5875402232  电子产品   路由器     9  299  2691
0  6805677496  家居用品    枕头    10  199  1990

In [4]:
# 数据分组
df.groupby("产品类别")["销售额"].count()  # 计算每个产品类别下的订单数量
df.groupby("产品类别")['销售额'].sum()  # 计算每个产品类别下的销售额总和
df.groupby("产品类别")["销售额"].mean()  # 计算每个产品类别下的销售额平均值
df.groupby("产品类别")["销售额"].max()  # 计算每个产品类别下的销售额最大值
df.groupby("产品类别")["销售额"].min()  # 计算每个产品类别下的销售额最小值
df.groupby("产品类别")["销售额"].agg(["mean", "max", "min"])  # 计算每个产品类别下的销售额平均值、最大值、最小值
df.groupby("产品类别").agg({"销售数量": 'sum', "销售额": 'sum', '单价': 'mean'})  # 计算每个产品类别下的销售数量总和、销售额总和、单价平均值

      销售数量   销售额          单价
产品类别
图书       6   314   64.000000
家居用品    10  1990  199.000000
服装      13   991   85.000000
电子产品    14  4686  349.000000
食品      10   270   25.666667